### PR TITLE
symlink helm charts crd definition to the operator's one

### PR DESCRIPTION
**Pull request by kevincai**

### CODE REVIEW

**Review by dengliu — COMMENTED** [review]
have you verified if helm support referring files that are not under the chart directory?

**Comment by kevincai** [comment]
will check it.

**Comment by yandongxiao** [comment]
I have checked it. When you use `helm package` to create chart，It will detect it.

```
walk.go:74: found symbolic link in path: /tmp/starrocks-kubernetes-operator/helm-charts/charts/kube-starrocks/crds/starrocks.com_starrocksclusters.yaml resolves to /private/tmp/starrocks-kubernetes-operator/deploy/starrocks.com_starrocksclusters.yaml. Contents of linked file included and used
Successfully packaged chart and saved it to: target/kube-starrocks-1.6.1.tgz
```

**Comment by kevincai** [comment]
> 

so it's fine then?

**Comment by yandongxiao** [comment]
> > 
> 
> so it's fine then?

yes

**Review by yandongxiao — APPROVED** [review]

**Pull request merged**
