### PR TITLE
[Enhancement] Properly set password when deployed by Argo CD

### PR DESCRIPTION
**Pull request by yandongxiao**
# Description

see #606 

# Checklist

For helm chart, please complete the following checklist:

- [x] make sure you have updated the [values.yaml](../helm-charts/charts/kube-starrocks/charts/starrocks/values.yaml)
  file of starrocks chart.
- [x] In `scripts` directory, run `bash create-parent-chart-values.sh` to update the values.yaml file of the parent
  chart( kube-starrocks chart).

### CODE REVIEW

**Review by kevincai — APPROVED** [review]

**Review by dengliu — APPROVED** [review]
Thanks for the fix!

**Comment by dengliu** [comment]
@yandongxiao  can you please cut a new helm chart release to include this fix?
Thank you!

**Comment by yandongxiao** [comment]
According to the rhythm of releasing new versions approximately every two months, we plan to release a new version at the end of this month.  Is it ok?

**Comment by dengliu** [comment]
We can wait till end of this month.
Can we make sure [this](https://github.com/StarRocks/starrocks-kubernetes-operator/issues/540) is also address in this release ?
Thank you!

**Pull request merged**
