### PR TITLE
[Bugfix] support k8s env which has no status.hostIP field

### PR DESCRIPTION
**Pull request by dujl**
In some serverless k8s env ,there is no status.hostIP field, and we do not use hostIp in StarRocks， so remove it.

### CODE REVIEW

**Comment by yandongxiao** [comment]
Please sign the CLA

**Comment by yandongxiao** [comment]
Direct deletion could lead to backward compatibility issues. Can we determine whether to add this environment variable by inspecting the status.hostIP field?

**Comment by dujl** [comment]
> Direct deletion could lead to backward compatibility issues. Can we determine whether to add this environment variable by inspecting the status.hostIP field?

it is a redundancy field. Env var HOST_IP doesn't be used in starrocks

**Comment by kevincai** [comment]
so the operator cr or helm chart values need an update as well?

**Review by yandongxiao — APPROVED** [review]

**Review by kevincai — APPROVED** [review]

**Pull request merged**
