### PR TITLE
[WIP][Enhancement] move CRD yaml file to templates directory

### PR DESCRIPTION
**Pull request by yandongxiao**
# Related Issue(s)
fixes: #448

### CODE REVIEW

**Review by mingmxu — APPROVED** [review]

**Comment by yandongxiao** [comment]
There are errors when execute `helm upgrade`.

Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: CustomResourceDefinition "starrocksclusters.starrocks.com" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "starrocks"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "starrocks"

**Comment by mingmxu** [comment]
I'm surprised that helm doesn't add the annotations when it's saved in `/crds` folder. As `helm upgrade` is not a valid way so far, I won't call it a break change, but it does worth to highlight in the next release version that:
* from v1.9.3 and later, `helm upgrade` is supported;
* for v1.9.2 or earlier -> v1.9.3, needs to run the two commands manually.

**Comment by yandongxiao** [comment]
> I'm surprised that helm doesn't add the annotations when it's saved in `/crds` folder. As `helm upgrade` is not a valid way so far, I won't call it a break change, but it does worth to highlight in the next release version that:
> 
> * from v1.9.3 and later, `helm upgrade` is supported;
> * for v1.9.2 or earlier -> v1.9.3, needs to run the two commands manually.

I think your suggestion is acceptable. @kevincai

**Comment by yandongxiao** [comment]
‌‌Close this PR first to prevent it from being merged.

**Pull request closed without merging**
